[package]
name = "cjson-rs-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.cjson_rs]
path = ".."

[[bin]]
name = "cjson_read_fuzzer"
path = "fuzz_targets/cjson_read_fuzzer.rs"
test = false
doc = false
bench = false
